security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    authorization:
      check-token-access: "isAuthenticated()"

logging:
  level:
    org.springframework.security: DEBUG
